name: assignment3

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm install mocha
      - run: npm test

  build:
    needs: unit_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate log.txt
        run: |
          echo "$(date --iso-8601=minutes)" > log.txt
          echo "Tommy Ben-Shaul" >> log.txt

      - name: Build the Docker image
        run: |
          if docker build -t exercise3 .; then
            echo "image successfully built" >> log.txt
          else
            echo "image not able to be built" >> log.txt
          fi

      - name: Save Docker image
        run: |
          docker save exercise3 > exercise3.tar


      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: exercise3-image
          path: exercise3.tar

      - name: Upload log file
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: log.txt
          path: log.txt

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download log file
        uses: actions/download-artifact@v3
        with:
          name: log.txt

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest requests

      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: exercise3-image

      - name: Run Docker image
        run: |
          docker load < exercise3.tar
          if docker run -d -p 8000:8000 exercise3; then
            echo "Container up and running" >> log.txt
            sleep 10
          else
            echo "Container failed to run" >> log.txt
          fi

      - name: Run tests and capture output
        id: tests
        run: |
          pytest -v tests/assn3_tests.py > assn3_test_results.txt || echo "tests_fail=true" >> $GITHUB_ENV

      - name: Capture pytest exit code
        run: echo "PYTEST_EXIT_CODE=${{ steps.tests.outcome }}"


      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: assn3_test_results.txt
          path: assn3_test_results.txt

      - name: Generate log for test result
        run: |
          if [[ "${{ env.tests_fail }}" == "true" ]]; then
            echo "tests failed" >> log.txt
          else
            echo "tests succeeded" >> log.txt
          fi


      - name: Upload log file
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: log.txt
          path: log.txt

  query:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install axios


      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: exercise3-image

      - name: Run Docker image
        run: |
          docker load < exercise3.tar
          docker run -d -p 8000:8000 exercise3
          sleep 10

      - name: delete old Docker image
        uses: geekyeggo/delete-artifact@v2
        with:
          name: exercise3-image

      - name: Query service
        run: node .github/ci-resources/query.js


      - name: Upload response file
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: response.txt
          path: .github/ci-resources/response.txt
